# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: CmdLine@2
    inputs:
      script: |
        sudo echo "$(Build.BuildNumber)" This is the buildnumber of publish_artifact > build.txt
        cat build.txt
  - task: CopyFiles@2
    displayName: 'Copy scripts'
    inputs:
        contents: '*.txt'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

  - publish: '$(Build.ArtifactStagingDirectory)/build.txt'
    displayName: 'Publish Artifact'
    artifact: app1